# Aligning sequences GGCT and GGATT using Needleman–Wunsch Method


In [ ]:
import numpy as np


## Initialise the matrix



In [ ]:
dna_seq1 = 'GGATT'
dna_seq2 = 'GGCT'

len_seq1 = len(dna_seq1)
len_seq2 = len(dna_seq2)


#Initialise matrix
alignment_score = np.zeros((len_seq1+1, len_seq2+1), dtype=int)
gap_penalty = -2  # Gap penalty is set to -2
backtrace = {}  # Dictionary to store backtrace pointers


## Matrix Fill Step

In [ ]:
print("Filling the matrix row wise and getting score values at each step in the form:")
print("M(i,j): max(diagonal score, left score, top score)\n")
# Populate the Score matrix
for index1 in range(1, len_seq1+1):
    for index2 in range(1, len_seq2+1):

        # Mismatch score is -1
        local_score = -1

        # Check for a match and set score to 2 if true
        if dna_seq1[index1-1] == dna_seq2[index2-1]:
            local_score = 2


        # Calculate possible alignment scores for current cell
        choices = [
            alignment_score[index1-1, index2-1] + local_score,
            alignment_score[index1, index2-1] + gap_penalty,
            alignment_score[index1-1, index2] + gap_penalty
        ]
        # Get the maximum score among the choices
        max_score = max(choices)
        max_index = choices.index(max_score)

        # Update the score in the current cell
        alignment_score[index1, index2] = max_score

        print('M({},{}): max{}'.format(index1, index2,choices))
        print("Matrix Status")
        print(alignment_score, "\n")

        # Store the backtrace information
        backtrace[(index1, index2)] = [
            (index1-1, index2-1),
            (index1, index2-1),
            (index1-1, index2)
        ][max_index]





Filling the matrix row wise and getting score values at each step in the form:
M(i,j): max(diagonal score, left score, top score)

M(1,1): max[2, -2, -2]
Matrix Status
[[0 0 0 0 0]
 [0 2 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

M(1,2): max[2, 0, -2]
Matrix Status
[[0 0 0 0 0]
 [0 2 2 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

M(1,3): max[-1, 0, -2]
Matrix Status
[[0 0 0 0 0]
 [0 2 2 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

M(1,4): max[-1, -2, -2]
Matrix Status
[[ 0  0  0  0  0]
 [ 0  2  2  0 -1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]] 

M(2,1): max[2, -2, 0]
Matrix Status
[[ 0  0  0  0  0]
 [ 0  2  2  0 -1]
 [ 0  2  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]] 

M(2,2): max[4, 0, 0]
Matrix Status
[[ 0  0  0  0  0]
 [ 0  2  2  0 -1]
 [ 0  2  4  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]] 

M(2,3): max[1, 2, -2]
Matrix Status
[[ 0  0  0  0  0]
 [ 0  2  2  0 -1]
 [

In [ ]:
print("Final Alignment Score Matrix:\n")
print(alignment_score)



Final Alignment Score Matrix:

[[ 0  0  0  0  0]
 [ 0  2  2  0 -1]
 [ 0  2  4  2  0]
 [ 0  0  2  3  1]
 [ 0 -1  0  1  5]
 [ 0 -1 -2 -1  3]]


In [ ]:

# Initialize variables for backtracing

current_index1, current_index2 = len_seq1, len_seq2
trace_path = [(current_index1, current_index2)]

# Perform backtracing to construct the alignment
while current_index1 > 1 and current_index2 > 1:
    current_index1, current_index2 = backtrace[(current_index1, current_index2)]
    trace_path.append((current_index1, current_index2))

prev_index1, prev_index2 = 0, 0

# Initialize variables for storing aligned sequences
aligned_seq1, aligned_seq2 = '', ''

# Create aligned sequences based on the trace path
for index1, index2 in reversed(trace_path):
    char1 = dna_seq1[index1-1] if index1 != prev_index1 else '_'
    char2 = dna_seq2[index2-1] if index2 != prev_index2 else '_'
    prev_index1, prev_index2 = index1, index2
    aligned_seq1 += char1
    aligned_seq2 += char2

print("Aligned dna_seq1:", aligned_seq1)
print("Aligned dna_seq2:", aligned_seq2)

Aligned dna_seq1: GGATT
Aligned dna_seq2: GG_CT
